- name: My first play
  hosts: GrandOS
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Create server directory
     become: yes
     ansible.builtin.file:
       path: /server
       state: directory
       mode: '0755'
       owner: grandos
       group: grandos

   - name: Send Server code
     ansible.builtin.copy:
      src: ui_server/
      dest: /server/
      backup: yes

   - name: Install build dependencies
     become: yes
     ansible.builtin.apt:
       update_cache: yes
       state: present
       name:
         - build-essential
         - cmake
         - pkg-config
         - libwebsockets-dev